receivers:
  otlp:
    protocols:
      http:
      grpc:
    
exporters:
  logging:

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  telemetry:
    logs:
      level: debug
